<?xml version="1.0" encoding="utf-8"?><Database Name="PaperSellMng" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=windows\sqlexpress;Initial Catalog=PaperSellMng;Integrated Security=True" SettingsObjectName="ProjectPaperSellManager.Properties.Settings" SettingsPropertyName="PaperSellMngConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietNhap" Member="ChiTietNhaps">
    <Type Name="ChiTietNhap">
      <Column Name="MaNhap" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMH" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="MatHang_ChiTietNhap" Member="MatHang" ThisKey="MaMH" OtherKey="MaMH" Type="MatHang" IsForeignKey="true" />
      <Association Name="NhapHang_ChiTietNhap" Member="NhapHang" ThisKey="MaNhap" OtherKey="MaNhap" Type="NhapHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietXuat" Member="ChiTietXuats">
    <Type Name="ChiTietXuat">
      <Column Name="MaHD" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMH" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="MatHang_ChiTietXuat" Member="MatHang" ThisKey="MaMH" OtherKey="MaMH" Type="MatHang" IsForeignKey="true" />
      <Association Name="XuatHang_ChiTietXuat" Member="XuatHang" ThisKey="MaHD" OtherKey="MaHD" Type="XuatHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatHang" Member="MatHangs">
    <Type Name="MatHang">
      <Column Name="MaMH" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonGiaNhap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGiaBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KichThuoc" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="DinhLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MatHang_ChiTietNhap" Member="ChiTietNhaps" ThisKey="MaMH" OtherKey="MaMH" Type="ChiTietNhap" />
      <Association Name="MatHang_ChiTietXuat" Member="ChiTietXuats" ThisKey="MaMH" OtherKey="MaMH" Type="ChiTietXuat" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="NhaCungCap_NhapHang" Member="NhapHangs" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhapHang" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_XuatHang" Member="XuatHangs" ThisKey="MaNV" OtherKey="MaNV" Type="XuatHang" />
    </Type>
  </Table>
  <Table Name="dbo.NhapHang" Member="NhapHangs">
    <Type Name="NhapHang">
      <Column Name="MaNhap" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="NhapHang_ChiTietNhap" Member="ChiTietNhaps" ThisKey="MaNhap" OtherKey="MaNhap" Type="ChiTietNhap" />
      <Association Name="NhaCungCap_NhapHang" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XuatHang" Member="XuatHangs">
    <Type Name="XuatHang">
      <Column Name="MaHD" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="NgayMua" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="XuatHang_ChiTietXuat" Member="ChiTietXuats" ThisKey="MaHD" OtherKey="MaHD" Type="ChiTietXuat" />
      <Association Name="NhanVien_XuatHang" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>